src/WebApp/ViewModels/StartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.ViewModels
{
    public class StartViewModel
    {
    }
}

src/WebApp/Controllers/StartController.cs
using System;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class StartController : Controller
    {
        public IActionResult Index()
        {
            var model = new StartViewModel();
            return View("Index", model);
        }

        [HttpPost]
        public IActionResult GetPartcipant(Participant participant)
        {
            // check in the db if participant exists
            // if yes: show new form where user enters email and saves it to the db
            throw new NotImplementedException();
        }
    }
}

src/WebApp/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Streaming Electron</title>
    <link href="~/static/css/main.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_PageHeader")

    <div>
        @RenderBody()
    </div>

    @Html.Partial("_Scripts")
    @RenderSection("scripts", required: false)
</body>
</html>

src/WebApp/Views/Shared/_PageFooter.cshtml
<footer class="row">
    
</footer>

src/WebApp/Views/Shared/_PageHeader.cshtml
<header class="row se-header">
    <div class="large-5 columns">
        <span class="sitelogo">{Streaming Electron}</span>
    </div>
    <div class="large-1 columns login">
        <a hreh="#">Log in</a>
    </div>
</header>

src/WebApp/Views/Shared/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/what-input/what-input.js"></script>
<script src="~/lib/foundation-sites/dist/foundation.js"></script>

<script>$(document).foundation();</script>

src/WebApp/Views/Start/Index.cshtml
@model WebApp.ViewModels.StartViewModel

<div class="row xy-center">
    <form asp-controller="Start" asp-action="GetPartcipant">
        <div class="large-8 columns">
            <input type="text" />
        </div>
        <div class="large-4 columns">
            <input type="submit" value="submit" class="button" />
        </div>
    </form>
</div>